#!/usr/bin/perl

use strict;
use warnings; 
use File::Basename qw(dirname);
use Cwd qw(abs_path);
use lib dirname(dirname abs_path $0) . '/lib';
use feature qw(say);

use My::ww qw(get_world_writable unset_world_writable); 

sub check_user {
    my $username = getpwuid($<);
    if ($username !~ "root") {
        print "Must run as root or via sudo. Exiting.\n";
        exit 1;
    }
}

check_user(); 

my $args = @ARGV;

if (!$args) {
    say "Usage: ./fww [dir] [--verbose]"; 
    say "       ./fww /tmp --verbose"; 
    say " -or-  ./fww /tmp"; 
    exit 1;
}

my ($dir, $verbose) = @ARGV;

if (!$dir) {
    say "No directory supplied. Exiting.";
    exit 1;
}

if ($dir and !$verbose) {
    my @list = get_world_writable($dir);
    for (@list) {
        say "$_";
    }
    
    for (@list) {
        unset_world_writable($_); 
    }
    exit 1;
} 

if ($dir and $verbose =~ /--verbose/) {
    my @list = get_world_writable($dir);
    for (@list) {
        say "$_: file is globally writable."
    }

    for (@list) {
        say "$_: disabling global write permission."; 
        unset_world_writable($_); 
    }
}
