#!/usr/bin/perl

use strict;
use warnings; 
use File::Basename qw(dirname);
use Cwd qw(abs_path);
use lib dirname(dirname abs_path $0) . '/lib';
use feature qw(say); 

use My::ww qw(get_world_writable unset_world_writable); 

my $args = @ARGV;

if (!$args) {
    say "Usage: ./fww_euid [dir] [--verbose] [userid]";
    exit 1;
}

my ($dir, $verbose, $user) = @ARGV;

if (!$user) {
    print "Must supply a userid for this script.\n"; 
    exit 1;
}

my $uid = getpwnam($user);
$> = $uid;

if (!$dir) {
    say "No directory supplied. Exiting.";
    exit 1;
}

if ($dir and !$verbose) {
    my @list = get_world_writable($dir);
    for (@list) {
        say "$_"; 
    }
    
    for (@list) {
        unset_world_writable($_); 
    }
    exit 1;
} 

if ($dir and $verbose =~ /--verbose/) {
    my @list = get_world_writable($dir);
    for (@list) {
        say "$_: file is globally writable."; 
    }

    for (@list) {
        say "$_: disabling global write permission.";
        unset_world_writable($_); 
    }
}
