#!/usr/bin/perl

use strict;
use warnings;
use Test::More;
use File::Basename qw(dirname);
use Cwd qw(abs_path);
use lib dirname(dirname abs_path $0) . '/lib';

use My::ww qw(get_world_writable_files unset_world_writable); 


BEGIN { use_ok("My::ww") }
can_ok("My::ww", "get_world_writable_files");
can_ok("My::ww", "unset_world_writable");

mkdir "/tmp/test";

chmod 0777, "/tmp/test/*"; 

my $dir = "/tmp/test";
my $verbose = 0;

my $find_world_writable = My::ww::get_world_writable_files($dir, $verbose);
my $unset_world_writable = My::ww::unset_world_writable($dir, $verbose);

done_testing;
